# samd21 is a Cortex-M0 and thus thumbv6m
# NickP: this is generic config for the ATSAMD21 chips

[alias]
# debug = "run --target thumbv6m-none-eabi --exec 'probe-rs debug --chip ATSAMD21G18A'"

[build]
target = "thumbv6m-none-eabi"

[target.thumbv6m-none-eabi]
# runner = 'arm-none-eabi-gdb'
runner = 'probe-rs run --chip ATSAMD21G18A'

rustflags = [

  # This is needed if your flash or ram addresses are not aligned to 0x10000 in memory.x
  # See https://github.com/rust-embedded/cortex-m-quickstart/pull/95
  "-C",
  "link-arg=--nmagic",

  "-C",
  "link-arg=-Tlink.x",

  # The defmt docs said so
  "-C",
  "link-arg=-Tdefmt.x",
]

[env]
DEFMT_LOG = "debug"
